### ISSUE TITLE
Invalid State Error on /Callback with the PHP Quick-Start SDK

### ISSUE THREAD

**Issue by DaDukyDev** [auth0-samples/auth0-php-web-app#73] opened 2021-11-15 10:06 UTC
Hey there,
this is a problem I think others have been facing, but I couldn’t find a conclusive answer. I am using the quick-start php project, and whenever I log in, I get the following PHP error on /callback

`Fatal error: Uncaught Auth0\SDK\Exception\StateException: Invalid state in /Users/timothytownsend/Desktop/auth0/vendor/auth0/auth0-php/src/Exception/StateException.php:24 Stack trace: #0 /Users/timothytownsend/Desktop/auth0/vendor/auth0/auth0-php/src/Auth0.php(323): Auth0\SDK\Exception\StateException::invalidState() #1 /Users/timothytownsend/Desktop/auth0/index.php(52): Auth0\SDK\Auth0->exchange('http://127.0.0....') #2 [internal function]: {closure}() #3 /Users/timothytownsend/Desktop/auth0/vendor/steampixel/simple-php-router/src/Steampixel/Route.php(103): call_user_func_array(Object(Closure), Array) #4 /Users/timothytownsend/Desktop/auth0/index.php(64): Steampixel\Route::run('') #5 {main} thrown in /Users/timothytownsend/Desktop/auth0/vendor/auth0/auth0-php/src/Exception/StateException.php on line 24`
Everything looks to be installed correctly, so I am not sure why it won’t work. I've followed the guide carefully, as this is just to familiarise myself with the platform's functions.
If anyone has any answers, that would be great.
Thanks, Tim

**Comment by evansims** [comment] 2021-11-16 02:37
Hi Tim,

An "Invalid State" is thrown when the SDK is unable to validate the `state` provided by Auth0 with what was stored on the client during the `login()` call.

- Most commonly this happens when the sample is run locally and the user invokes the app from a URL that differs from the callback URL, such as starting login at localhost:3000 and being returned to 127.0.0.1:3000; as far as cookies are concerned, those are separate domains and an invalid state is correctly thrown.
- Open your browser developer tools and enable logging to ensure the cookie is being set and stored correctly.

**Comment by DaDukyDev** [comment] 2021-11-16 02:57
I've configured the callbacks, etc. correctly, and everything is fine. It doesn't look like any cookies are in use on the 127.0.0.1:3000 instance, though. No error but the one above

**Comment by evansims** [comment] 2021-11-16 03:07
What URL are you invoking the app from? What are your callbacks setup as?
Can you break down your configuration for me?
What does your environment file look like (sans any secrets, of course)?
What browser are you using?

**Comment by DaDukyDev** [comment] 2021-11-16 03:23
I am invoking the app from http://127.0.0.1:3000/, the callbacks are set up as /login and /callback respectively. The config is quite literally just a copy-and-paste walkthrough from the quickstart guide, as I'm just familiarising myself with the setup of Auth0. In terms of .env file, I've attached it below, and I'm using google chro
[ENV.txt](https://github.com/auth0-samples/auth0-php-web-app/files/7543110/ENV.txt)
me

**Comment by evansims** [comment] 2021-11-16 03:42
Hmm strange, I'm just unable to reproduce what you're seeing here, sorry.

In the sample application, the `login()` call on line 236 of `Application.php` should be creating a cookie in your browser. This is stored temporarily and is deleted upon callback, when `exchange()` is called on line 215 of the same file. If I intercept the callback route and add the following before the exchange using:

```php
/**
 * Called from the ApplicationRouter when end user loads '/callback'.
 */
public function onCallbackRoute(
    ApplicationRouter $router
): void {
    // If you have an example class enabled ("AUTH0_EXAMPLE" in your .env file), check if a hook is setup to override default behavior:
    $event = $this->exampleHooks['onCallbackRoute'] ?? null;

    if ($event === null || $event($router) === null) {
        // Intercept and render debug data to browser.
        echo '<pre>';
        print_r($_COOKIE);
        print_r($_SERVER);
        exit;

        // Inform Auth0 we want to redirect to our /callback route, so we can perform the code exchange and setup the user session there.
        $this->sdk->exchange($router->getUri('/callback', ''));

        // Redirect to your application's index route.
        $router->redirect($router->getUri('/', ''));
    }
}
```

I see the following:
![image](https://user-images.githubusercontent.com/3093/141891781-89c8e452-dfe9-4602-a908-b776ee7e2c7c.png)

Could you do the same and verify if $_COOKIE contains anything for you, before `exchange` is called? (It won't be there after the fact.)

**Comment by DaDukyDev** [comment] 2021-11-16 04:23
I am not actually downloading the sample app. I've just used that basic setup guide below the sample. It doesn't look like $_COOKIE is anyway

**Comment by DaDukyDev** [comment] 2021-11-21 22:54
Hey there, is there any update so far?

**Comment by evansims** [comment] 2021-11-29 06:12
What setup guide are you referring to specifically?

**Comment by evansims** [comment] 2021-12-07 00:54
Going to close this for now, please let me know if your issues have persisted, and we can try to troubleshoot further. Thanks!

**Closed by evansims** 2021-12-07 00:54 UTC
